export const TOGGLE_SHIELD_MAIN_HEADER = 'TOGGLE_SHIELD_MAIN_HEADER';
export const TOGGLE_SHIELD_SUB_HEADER = 'TOGGLE_SHIELD_SUB_HEADER';
export const TOGGLE_SHIELD_PART_COLLECTED = 'TOGGLE_SHIELD_PART_COLLECTED';

export const TOGGLE_SECRET_DOOR_MAIN_HEADER = 'TOGGLE_SECRET_DOOR_MAIN_HEADER';
export const TOGGLE_SECRET_DOOR_SUB_HEADER = 'TOGGLE_SECRET_DOOR_SUB_HEADER';
export const TOGGLE_SECRET_DOOR_COMPLETED = 'TOGGLE_SECRET_DOOR_COMPLETED';